all:
	make setup

part1:
	gcc part1.c stack.c -o part1.out
	./part1.out

part2:
	gcc part2.c stack.c -o part2.out
	./part2.out

setup:
	touch part1.c
	touch part2.c
	touch example.txt
	touch sample.txt
